# Generated by Django 4.0.5 on 2023-05-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='profiles')),
                ('address', models.CharField(max_length=300)),
                ('time_line_pic', models.ImageField(null=True, upload_to='image')),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
