# Generated by Django 4.0.5 on 2023-05-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='time_line_pic',
        ),
    ]
