# Generated by Django 4.0.5 on 2023-05-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_userprofile_time_line_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
