# Generated by Django 4.0.5 on 2023-05-22 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0002_alter_orders_expected_deliverydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 5, 27)),
        ),
        migrations.CreateModel(
            name='CameraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('decription', models.CharField(max_length=200)),
                ('price', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('camera_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.camera')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.category')),
            ],
        ),
    ]
