# Generated by Django 4.0.5 on 2023-05-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0003_alter_orders_expected_deliverydate_cameradetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameradetails',
            old_name='camera_name',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='category',
            new_name='categor',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='decription',
            new_name='decriptio',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='is_active',
            new_name='is_actives',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='price',
            new_name='rs',
        ),
    ]
