# Generated by Django 4.0.5 on 2023-05-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0004_rename_camera_name_cameradetails_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameradetails',
            old_name='images',
            new_name='imge',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='is_actives',
            new_name='is_ctive',
        ),
        migrations.RenameField(
            model_name='cameradetails',
            old_name='rs',
            new_name='pric',
        ),
    ]
