# Generated by Django 4.0.5 on 2023-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0005_rename_images_cameradetails_imge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradetails',
            name='company',
            field=models.CharField(choices=[('Canon', 'Canon'), ('Sony', 'Sony'), ('Panasonic', 'Panasonic'), ('Nikon', 'Nikon'), ('Fujifilm', 'Fujifilm'), ('Olympus', 'Olympus')], max_length=300),
        ),
    ]
