# Generated by Django 4.0.5 on 2023-05-24 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0007_alter_camera_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 5, 29)),
        ),
        migrations.DeleteModel(
            name='CameraDetails',
        ),
    ]
