# Generated by Django 4.0.5 on 2023-05-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0009_alter_orders_expected_deliverydate_partscart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partscart',
            name='productparts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam.cameraparts'),
        ),
    ]
