# Generated by Django 4.0.5 on 2023-05-27 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0010_alter_partscart_productparts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partscart',
            name='productparts',
        ),
        migrations.RemoveField(
            model_name='partscart',
            name='user',
        ),
        migrations.AddField(
            model_name='camera',
            name='spares_parts',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 6, 1)),
        ),
        migrations.DeleteModel(
            name='Cameraparts',
        ),
        migrations.DeleteModel(
            name='PartsCart',
        ),
    ]
