# Generated by Django 4.0.5 on 2023-05-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0011_remove_partscart_productparts_remove_partscart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='spares_parts',
        ),
    ]
