# Generated by Django 4.0.5 on 2023-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0012_remove_camera_spares_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offerPoint',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
