# Generated by Django 4.0.5 on 2023-05-28 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0016_rename_camera_name_specialproduct_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialproduct',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='offerPoint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
