# Generated by Django 4.0.5 on 2023-05-31 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0019_alter_specialorders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 6, 5)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 6, 5)),
        ),
    ]
