# Generated by Django 4.0.5 on 2023-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0020_alter_orders_expected_deliverydate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=260, null=True)),
            ],
        ),
    ]
