# Generated by Django 4.0.5 on 2023-05-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0021_addressview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressView',
            new_name='Address',
        ),
    ]
