# Generated by Django 4.0.5 on 2023-05-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0022_rename_addressview_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
