# Generated by Django 4.0.5 on 2023-06-01 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0024_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
    ]
