# Generated by Django 4.0.5 on 2023-06-02 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam', '0025_alter_billing_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 6, 7)),
        ),
        migrations.AlterField(
            model_name='specialorders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 6, 7)),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
